name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todo dia à meia-noite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: 0M1n40
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit e Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Atualizando cobrinha"
          git push
